export const CATEGORIES: string[] = [
  "JOKER", "ELŐNYBEN RÉSZESÍTÉS", "LAKHELY", "LAKCÍMIGAZOLÁS", "LAKCÍMKÁRTYA", "ELTARTÓ CSALÁDI ÁLLAPOTA/ SZEMÉLYE",
  "ELTARTÓ JÖVEDELME", "ELTARTOTT", "EGYÉB"
];
